// Realistic Nigerian-context mock data for admin panel development.
// Replace with live Supabase queries when real data is available.

export const MOCK_STATS = {
  totalCandidates: 1_842,
  totalCompanies: 284,
  verificationsToday: 47,
  pendingCandidates: 23,
  pendingCompanies: 8,
  flaggedItems: 14,
  activeJobListings: 512,
  applicationsToday: 189,
}

export const MOCK_REGISTRATION_TREND = [
  { date: '01 Jun', candidates: 45, companies: 8 },
  { date: '05 Jun', candidates: 72, companies: 12 },
  { date: '10 Jun', candidates: 61, companies: 9 },
  { date: '15 Jun', candidates: 89, companies: 15 },
  { date: '20 Jun', candidates: 134, companies: 22 },
  { date: '25 Jun', candidates: 97, companies: 18 },
]

export const MOCK_CANDIDATE_QUEUE = [
  {
    id: 'c001',
    name: 'Adaeze Nwosu',
    email: 'adaeze.nwosu@gmail.com',
    submittedAt: '2026-06-25T06:12:00Z',
    ninMatch: true,
    livenessPass: true,
    docScan: 'passed' as const,
    trustScore: 78,
    ninLast4: '****7823',
    phone: '+234 803 421 9900',
    documents: ['certificate_hnd.pdf', 'waec_result.jpg'],
  },
  {
    id: 'c002',
    name: 'Chukwuemeka Obi',
    email: 'emeka.obi@outlook.com',
    submittedAt: '2026-06-25T05:44:00Z',
    ninMatch: false,
    livenessPass: true,
    docScan: 'flagged' as const,
    trustScore: 32,
    ninLast4: '****4411',
    phone: '+234 806 543 2211',
    documents: ['bsc_certificate.pdf'],
  },
  {
    id: 'c003',
    name: 'Funmilayo Adeleke',
    email: 'funmi.adeleke@yahoo.com',
    submittedAt: '2026-06-24T22:31:00Z',
    ninMatch: true,
    livenessPass: true,
    docScan: 'passed' as const,
    trustScore: 85,
    ninLast4: '****9921',
    phone: '+234 812 774 0032',
    documents: ['masters_degree.pdf', 'nysc_certificate.jpg'],
  },
  {
    id: 'c004',
    name: 'Ibrahim Musa',
    email: 'ibrahim.musa@gmail.com',
    submittedAt: '2026-06-24T20:15:00Z',
    ninMatch: true,
    livenessPass: false,
    docScan: 'pending' as const,
    trustScore: 41,
    ninLast4: '****3301',
    phone: '+234 818 234 5670',
    documents: ['bsc_certificate.pdf', 'secondary_cert.jpg'],
  },
]

export const MOCK_COMPANY_QUEUE = [
  {
    id: 'co001',
    name: 'TechBridge Solutions Ltd',
    rcNumber: 'RC-1847293',
    email: 'hr@techbridge.ng',
    submittedAt: '2026-06-25T07:02:00Z',
    cacMatch: true,
    directorNinMatch: true,
    docScan: 'passed' as const,
    industry: 'Technology',
    size: '51_200',
    documents: ['cac_cert.pdf', 'address_proof.pdf'],
  },
  {
    id: 'co002',
    name: 'Lagos Logistics Hub',
    rcNumber: 'RC-0043812',
    email: 'admin@lagoslogistics.ng',
    submittedAt: '2026-06-25T04:30:00Z',
    cacMatch: false,
    directorNinMatch: true,
    docScan: 'flagged' as const,
    industry: 'Logistics',
    size: '11_50',
    documents: ['cac_cert.pdf'],
  },
  {
    id: 'co003',
    name: 'Greenfield Finance Advisory',
    rcNumber: 'RC-2210034',
    email: 'compliance@greenfieldfa.com',
    submittedAt: '2026-06-24T18:45:00Z',
    cacMatch: true,
    directorNinMatch: true,
    docScan: 'passed' as const,
    industry: 'Finance',
    size: '11_50',
    documents: ['cac_cert.pdf', 'address_proof.pdf', 'director_id.jpg'],
  },
]

export const MOCK_FLAGGED_ITEMS = [
  {
    id: 'f001',
    type: 'job_post' as const,
    title: 'Earn ₦500K weekly working from home',
    entity: 'Unknown Recruits Ltd',
    flagReason: 'Scam language patterns detected (unrealistic salary, work-from-home fraud)',
    confidence: 94,
    flaggedAt: '2026-06-25T08:01:00Z',
    context: 'Job posting contained phrases: "guaranteed income", "no experience needed", "WhatsApp only"',
  },
  {
    id: 'f002',
    type: 'document' as const,
    title: 'Tampered degree certificate upload',
    entity: 'Kelechi Eze (candidate)',
    flagReason: 'Document metadata mismatch — PDF creation date inconsistent with claimed graduation year',
    confidence: 87,
    flaggedAt: '2026-06-25T07:15:00Z',
    context: 'PDF metadata shows creation: 2024-11, claimed graduation: 2019',
  },
  {
    id: 'f003',
    type: 'behavior' as const,
    title: 'Mass application bot detected',
    entity: 'candidatex882@proton.me',
    flagReason: '73 applications submitted in 4 minutes 22 seconds',
    confidence: 99,
    flaggedAt: '2026-06-25T06:48:00Z',
    context: 'IP: 105.112.xxx.xxx — Lagos. Device fingerprint matches 3 previous banned accounts.',
  },
  {
    id: 'f004',
    type: 'ip_match' as const,
    title: 'Sanctioned IP range activity',
    entity: 'New registration: Abiodun Fakoya',
    flagReason: 'IP matches known fraud network range flagged by EFCC referral',
    confidence: 71,
    flaggedAt: '2026-06-25T05:22:00Z',
    context: 'IP block: 41.190.x.x/24 — flagged 2026-04-12',
  },
]

export const MOCK_USERS = [
  {
    id: 'u001',
    name: 'Adaeze Nwosu',
    email: 'adaeze.nwosu@gmail.com',
    role: 'candidate' as const,
    trustScore: 78,
    verificationStatus: 'approved' as const,
    registeredAt: '2026-06-20T09:00:00Z',
    lastLogin: '2026-06-25T07:30:00Z',
    isSuspended: false,
    applications: 12,
    location: 'Lagos',
  },
  {
    id: 'u002',
    name: 'TechBridge Solutions Ltd',
    email: 'hr@techbridge.ng',
    role: 'company' as const,
    trustScore: 91,
    verificationStatus: 'approved' as const,
    registeredAt: '2026-06-18T11:00:00Z',
    lastLogin: '2026-06-25T08:00:00Z',
    isSuspended: false,
    applications: 0,
    location: 'Lagos',
  },
  {
    id: 'u003',
    name: 'Chukwuemeka Obi',
    email: 'emeka.obi@outlook.com',
    role: 'candidate' as const,
    trustScore: 32,
    verificationStatus: 'pending' as const,
    registeredAt: '2026-06-24T14:00:00Z',
    lastLogin: '2026-06-25T05:44:00Z',
    isSuspended: false,
    applications: 3,
    location: 'Abuja',
  },
  {
    id: 'u004',
    name: 'candidatex882@proton.me',
    email: 'candidatex882@proton.me',
    role: 'candidate' as const,
    trustScore: 5,
    verificationStatus: 'rejected' as const,
    registeredAt: '2026-06-25T06:40:00Z',
    lastLogin: '2026-06-25T06:48:00Z',
    isSuspended: true,
    applications: 73,
    location: 'Unknown',
  },
]

export const MOCK_JOB_POSTS = [
  {
    id: 'j001',
    title: 'Earn ₦500K weekly working from home',
    company: 'Unknown Recruits Ltd',
    status: 'flagged' as const,
    postedAt: '2026-06-25T07:55:00Z',
    applications: 0,
    category: 'Other',
    flagReason: 'Scam language: unrealistic salary, informal contact only',
    confidence: 94,
  },
  {
    id: 'j002',
    title: 'Senior Software Engineer (React Native)',
    company: 'TechBridge Solutions Ltd',
    status: 'active' as const,
    postedAt: '2026-06-24T10:00:00Z',
    applications: 27,
    category: 'Technology',
    flagReason: null,
    confidence: null,
  },
  {
    id: 'j003',
    title: 'Logistics Coordinator',
    company: 'Lagos Logistics Hub',
    status: 'active' as const,
    postedAt: '2026-06-23T14:30:00Z',
    applications: 14,
    category: 'Logistics',
    flagReason: null,
    confidence: null,
  },
  {
    id: 'j004',
    title: 'Investment Analyst',
    company: 'Greenfield Finance Advisory',
    status: 'active' as const,
    postedAt: '2026-06-22T09:15:00Z',
    applications: 31,
    category: 'Finance',
    flagReason: null,
    confidence: null,
  },
]

export const MOCK_DISPUTES = [
  {
    id: 'd001',
    candidateName: 'Funmilayo Adeleke',
    candidateEmail: 'funmi.adeleke@yahoo.com',
    badgeFrom: 'TechBridge Solutions Ltd',
    badgeRole: 'Frontend Developer Intern',
    badgeDates: 'Jan 2024 – Jul 2024',
    reason: 'never_worked' as const,
    reasonLabel: 'I never worked at this company',
    description: 'I have no record of employment with TechBridge. This badge was issued without my knowledge and may be an error or fraud.',
    submittedAt: '2026-06-25T06:00:00Z',
    evidenceFiles: ['offer_letter_actual.pdf'],
    previousDisputes: 0,
  },
  {
    id: 'd002',
    candidateName: 'Ibrahim Musa',
    candidateEmail: 'ibrahim.musa@gmail.com',
    badgeFrom: 'Apex Manufacturing Co',
    badgeRole: 'Production Supervisor',
    badgeDates: 'Mar 2023 – Dec 2023',
    reason: 'wrong_dates' as const,
    reasonLabel: 'Wrong employment dates',
    description: 'I worked at Apex from March 2023 to February 2024, not December 2023 as shown.',
    submittedAt: '2026-06-24T19:20:00Z',
    evidenceFiles: [],
    previousDisputes: 1,
  },
]

export const MOCK_TICKETS = [
  {
    id: 't001',
    subject: 'Cannot complete NIN verification — page keeps crashing',
    category: 'technical' as const,
    userEmail: 'adaeze.nwosu@gmail.com',
    userName: 'Adaeze Nwosu',
    status: 'open' as const,
    priority: 'urgent' as const,
    submittedAt: '2026-06-25T07:55:00Z',
    message: 'Every time I try to submit my NIN, the app crashes on step 3. I have tried 4 times.',
    assignedTo: null,
  },
  {
    id: 't002',
    subject: 'Badge issued to wrong candidate profile',
    category: 'badge_dispute' as const,
    userEmail: 'hr@techbridge.ng',
    userName: 'TechBridge HR',
    status: 'in_progress' as const,
    priority: 'standard' as const,
    submittedAt: '2026-06-25T05:30:00Z',
    message: 'We issued a badge to candidate ID 00823 but it appears on profile 00281. Please correct.',
    assignedTo: 'admin@workstation.ng',
  },
  {
    id: 't003',
    subject: 'Job post removed without warning',
    category: 'moderation' as const,
    userEmail: 'admin@lagoslogistics.ng',
    userName: 'Lagos Logistics Hub',
    status: 'open' as const,
    priority: 'standard' as const,
    submittedAt: '2026-06-24T14:10:00Z',
    message: 'Our job listing for Warehouse Supervisor was removed. We did not receive any notification or reason.',
    assignedTo: null,
  },
  {
    id: 't004',
    subject: 'Subscription billing error — charged twice',
    category: 'billing' as const,
    userEmail: 'compliance@greenfieldfa.com',
    userName: 'Greenfield Finance',
    status: 'resolved' as const,
    priority: 'standard' as const,
    submittedAt: '2026-06-23T10:00:00Z',
    message: 'We were charged twice for our June subscription. Please issue a refund for the duplicate.',
    assignedTo: 'billing@workstation.ng',
  },
]

export const MOCK_PLATFORM_CONFIG = [
  // Trust score weights
  { key: 'trust_weight_nin', label: 'NIN verification weight', value: '35', group: 'trust', type: 'number' as const, description: 'Points added to trust score when NIN is verified' },
  { key: 'trust_weight_liveness', label: 'Liveness check weight', value: '25', group: 'trust', type: 'number' as const, description: 'Points for passing liveness / face match check' },
  { key: 'trust_weight_document', label: 'Document scan weight', value: '25', group: 'trust', type: 'number' as const, description: 'Points for passing document AI scan' },
  { key: 'trust_weight_employment', label: 'Employment history weight', value: '15', group: 'trust', type: 'number' as const, description: 'Points for verified employment history' },
  // Badge settings
  { key: 'badge_revocation_window_hours', label: 'Badge revocation window (hours)', value: '72', group: 'badges', type: 'number' as const, description: 'Hours after issuance during which company can revoke a badge' },
  // Email limits
  { key: 'email_daily_limit_per_company', label: 'Daily email limit per company', value: '500', group: 'email', type: 'number' as const, description: 'Maximum emails a company can send per calendar day' },
  // Dev settings
  { key: 'dev_mode_otp', label: 'Dev mode OTP', value: '123456', group: 'dev', type: 'string' as const, description: 'Fixed OTP for testing. Clear this in production.' },
  { key: 'verification_api_primary', label: 'Primary verification API', value: 'smile_identity', group: 'dev', type: 'string' as const, description: 'smile_identity | dojah' },
  // Feature flags
  { key: 'feature_video_v2', label: 'Video interviews (V2)', value: 'true', group: 'features', type: 'toggle' as const, description: 'Enable LiveKit video interview room for all users' },
  { key: 'feature_talent_search', label: 'Talent search (company)', value: 'true', group: 'features', type: 'toggle' as const, description: 'Allow companies to proactively browse candidate profiles' },
  { key: 'feature_payment_gates', label: 'Payment gates', value: 'false', group: 'features', type: 'toggle' as const, description: 'Require payment before companies can post jobs (launch mode = false)' },
  { key: 'feature_cv_builder', label: 'CV builder', value: 'true', group: 'features', type: 'toggle' as const, description: 'Enable CV builder tool for candidates' },
]
